version: '2.1'

services:
  Jack testing:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/Jack_test/Jack testing
    ports:
      - $SERVER_PORT:$SERVER_PORT
